### ISSUE TITLE
Pallet Resolution for Multiple Pages Causes Error

### ISSUE THREAD

**Issue by eliptus** [haven1433/HexManiacAdvance#100]
Whenever I attempt to import an image with multiple pages, if I select any pallet resolution option other than Cautious, I get this error.

Notes from crash.log: 

    Version Number:0.4.5
    Release Version
    11/26/2022 5:35:12 AM
    General Information:
    Current tab count: 2
    Current selected tab: 1
    Tab is ViewPort for Pokemon - Radical Red - v3.1.gba
    Game Code: BPRE0
    Data Length: 0x2000000
    Pokemon Count: 823
    ---
    Tab is ViewPort for Moemon - Mega Fire Red - v1.2b.gba
    Game Code: BPRE0
    Data Length: 0x2000000
    Pokemon Count: 412
    ---
    Exception Information:
    System.IndexOutOfRangeException
    Index was outside the bounds of the array.
       at HavenSoft.HexManiac.Core.ViewModels.Tools.SpriteTool.WriteSpritesAndPalette(ISpriteRun spriteRun, IPaletteRun paletteRun, Int16[][] images, IReadOnlyList`1 usablePalPages) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\Tools\SpriteTool.cs:line 0
       at HavenSoft.HexManiac.Core.ViewModels.Tools.SpriteTool.ImportTallSpriteAndPalette(IFileSystem fileSystem, Int16[] image, ISpriteRun spriteRun, IPaletteRun paletteRun) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\Tools\SpriteTool.cs:line 944
       at HavenSoft.HexManiac.Core.ViewModels.Tools.SpriteTool.ImportSpriteAndPalette(IFileSystem fileSystem) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\Tools\SpriteTool.cs:line 727
       at HavenSoft.HexManiac.Core.ViewModels.Tools.SpriteTool.<.ctor>b__158_8(Object arg) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\Tools\SpriteTool.cs:line 568
       at HavenSoft.HexManiac.Core.ViewModels.Tools.SpriteElementViewModel.ExecuteSpriteToolCommand(IFileSystem fs, ICommand command) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\Tools\SpriteElementViewModel.cs:line 153
       at HavenSoft.HexManiac.Core.ViewModels.Tools.SpriteElementViewModel.ExecuteImportImage(IFileSystem fs) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\Tools\SpriteElementViewModel.cs:line 102
       at HavenSoft.HexManiac.Core.ViewModels.ViewModelCore.<>c__DisplayClass14_0`1.<StubCommand>b__0(Object arg) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\ViewModelCore.cs:line 138
       at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Primitives.ToggleButton.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    
    -------------------------------------------

**Comment by eliptus** [comment]
This override is what's causing the truncation of the `newPalettes` array, which eventually results in the out-of-bounds:
https://github.com/haven1433/HexManiacAdvance/blob/8f3da7f04e2af6f83aa59487b940d2c2ef645ca3/src/HexManiac.Core/ViewModels/Tools/SpriteTool.cs#L1014

Not yet sure what the solution is, though.

**Comment by eliptus** [comment]
In case it's not clear, the intent in the import that causes this is to import four sprites with four different palettes, opting to Ignore the existing palettes.

**Comment by haven1433** [comment]
Fixed in [fix castform multisprite import logic](https://github.com/haven1433/HexManiacAdvance/commit/21ea2a66125ee01e21f462c99f1908fb6a6bb3fe), thanks for reporting!
