### ISSUE TITLE
Export all sprites not working on Moemon FireRed

### ISSUE THREAD

**Issue by rafaelsk1** [haven1433/HexManiacAdvance#147]
I keep trying to pull all the sprites at once, when I click All Table and then select the folder this error shows up and nothing happens.

Notes from crash.log: 

    Version Number:0.5.1
    Release Version
    4/18/2023 11:09:20 AM
    General Information:
    Current tab count: 1
    Current selected tab: 0
    Tab is ViewPort for MoemonFRcopy.gba
    Game Code: BPRE0
    Data Length: 0x2000000
    Pokemon Count: 412
    ---
    Exception Information:
    System.NullReferenceException
    Object reference not set to an instance of an object.
       at HavenSoft.HexManiac.Core.ViewModels.Tools.SpriteElementViewModel.ExecuteExportAllImages(IFileSystem fs) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\Tools\SpriteElementViewModel.cs:line 155
       at HavenSoft.HexManiac.Core.ViewModels.ViewModelCore.<>c__DisplayClass16_0`1.<StubCommand>b__0(Object arg) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\ViewModelCore.cs:line 153
       at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
       at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    
    -------------------------------------------
    
    It works with individual sprites though I'm doing it that way in the meantime.

**Comment by ShinyTillDawn** [comment]
Are there any sprites within the table of Pokémon sprites that are corrupted or have weird data?

It's possible that a different tool put the images in the game with different protocols, and HMA's methods to export `.png`s simultaneously just won't be able to do so for all of the Moemon sprites.

**Comment by rafaelsk1** [comment]
I haven't seen any weird data in any of the sprites hex, already managed to
export all of them one by one with no problems.

I'm about to use the sprites in a clean pokemon emerald rom to see if they
work properly

**Comment by haven1433** [comment]
I looked into this tonight and I'm pretty sure it's fixed now. It'll be in the 0.5.2 release, or you can build it locally to get the change right away.

**Comment by rafaelsk1** [comment]
Sounds good I managed to get all the sprites but it will be really useful
if I someone needs it, I'm gonna download it again and try it too thank you
