### ISSUE TITLE
Weird constant issue.

### ISSUE THREAD

**Issue by Draft-Fusion** [haven1433/HexManiacAdvance#166]
*(Please replace this section with notes about what you were doing or how to reproduce)*

Notes from crash.log: 

    Version Number: 0.5.2
    Release Version
    6/8/2023 6:00:07 PM
    General Information:
    Current tab count: 1
    Current selected tab: 0
    Tab is HavenSoft.HexManiac.Core.ViewModels.Map.MapEditorViewModel
    4-3 (PALLET TOWN)
    ---
    Exception Information:
    System.NullReferenceException
    Object reference not set to an instance of an object.
       at HavenSoft.HexManiac.Core.MethodCommand.Execute(Object parameter) in D:\root\GitHub\HexManiac\src\HexManiac.Core\MethodCommand.cs:line 100
       at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    
    -------------------------------------------

**Comment by haven1433** [comment]
> Please replace this section with notes about what you were doing or how to reproduce

Care to provide any more information about the bug?

**Comment by MechanicalDeus** [comment]
Unless I do Something awfully wrong (wich I dont think) the Map Editor is unusably broken right now. 
I have tried to recreate the steps done in the Map editing Tutorial thats listed Here and whenever IT comes to adding in Events it Just crashes

**Comment by haven1433** [comment]
This sounds/looks like an issue that's already been fixed in the latest source. You have a few options:
(1) Wait for release 0.5.3, which will be released when all known existing bugs are fixed.
(2) Download the source (or clone the repo) so you can build a version with all the latest changes.
(3) Join the [Discord Server](https://discord.gg/x9eQuBg) to get access to more recent debug beta builds that have this fix.

**Comment by haven1433** [comment]
Closing since this is fixed in the latest source.
