### ISSUE TITLE
Trainer export error, not sure what is going on here?

### ISSUE THREAD

**Issue by Draft-Fusion** [haven1433/HexManiacAdvance#167]
*(Please replace this section with notes about what you were doing or how to reproduce)*

Notes from crash.log: 

    Version Number: 0.5.2
    Release Version
    6/8/2023 6:13:25 PM
    General Information:
    Current tab count: 1
    Current selected tab: 0
    Tab is ViewPort for Pokemon - Fire Red Version (U) (V1.1).gba
    Game Code: BPRE1
    Data Length: 0x1000000
    Pokemon Count: 412
    ---
    Exception Information:
    System.ArgumentOutOfRangeException
    Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
    
       at System.SZArrayHelper.get_Item[T](Int32 index)
       at HavenSoft.HexManiac.Core.ViewModels.Tools.SpriteElementViewModel.ExecuteExportAllImages(IFileSystem fs) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\Tools\SpriteElementViewModel.cs:line 157
       at HavenSoft.HexManiac.Core.ViewModels.ViewModelCore.<>c__DisplayClass16_0`1.<StubCommand>b__0(Object arg) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\ViewModelCore.cs:line 153
       at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
       at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    
    -------------------------------------------

**Comment by haven1433** [comment]
> Please replace this section with notes about what you were doing or how to reproduce

Care to provide any more information about the bug?

**Comment by haven1433** [comment]
Closed for lack of information / activity. Exporting trainers from vanilla FireRed 1.1 works with no issue.
