### ISSUE TITLE
I was prompted to give a bug report by the App and so I am doing as such.

### ISSUE THREAD

**Issue by EnderOnryo** [haven1433/HexManiacAdvance#193]
I was going through the trainer back sprites and exporting them. I was exporting individually and in bulk to get a feel for how the tool worked. I'm not sure what even went wrong other than maybe exporting some of the sprites with the wrong pallet. (I hope this image copy paste embed works properly.
![image](https://github.com/haven1433/HexManiacAdvance/assets/89392609/63f3f440-ba4b-4f32-853d-328f4934cd1b)

Notes from crash.log: 

    Version Number: 0.5.3
    Debug Version
    25/08/2023 3:48:05 PM
    General Information:
    Current tab count: 1
    Current selected tab: 0
    ---
    Tab is ViewPort for Pokemon - Emerald Version (USA, Europe).gba
    Game Code: BPEE0
    Data Length: 0x1000000
    Pokemon Count: 412
    ---
    Exception Information:
    System.ArgumentOutOfRangeException
    Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
    
       at System.SZArrayHelper.get_Item[T](Int32 index)
       at HavenSoft.HexManiac.Core.ViewModels.Tools.SpriteElementViewModel.ExecuteExportAllImages(IFileSystem fs) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\Tools\SpriteElementViewModel.cs:line 165
       at HavenSoft.HexManiac.Core.ViewModels.ViewModelCore.<>c__DisplayClass20_0`1.<StubCommand>b__0(Object arg) in D:\root\GitHub\HexManiac\src\HexManiac.Core\ViewModels\ViewModelCore.cs:line 153
       at System.Windows.Input.StubCommand.System.Windows.Input.ICommand.Execute(Object parameter) in D:\root\GitHub\HexManiac\src\HexManiac.Core\Core\Autos\StubCommand.cs:line 30
       at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
       at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    
    -------------------------------------------

**Comment by EnderOnryo** [comment]
A separate or maybe related issue. If I do `Export` > `All Table` on the character back sprites some of them don't export but the ones that do export them all with the pallet of the currently selected character. In this case Wally.
![image](https://github.com/haven1433/HexManiacAdvance/assets/89392609/2be74ab6-0b6a-4245-b81d-928b3269d059)

**Comment by haven1433** [comment]
Thanks for reporting! I've fixed it in the latest commit. It'll be working correctly in the next release.
